services:
  postgres:
    image: postgres:16.8-alpine3.20
    container_name: fincheck-db
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: fincheck-node
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/fincheck-db"
    command: sh -c "yarn prisma migrate deploy && yarn start:prod"
    

